# Cache downloaded dependencies and plugins between builds.
# Not strictly necessary, but speeds up the builds.
cache:
    key: "$CI_JOB_NAME"
    paths:
        # Must be within the repository under test hence we can't use the
        # default ~/.m2
        - .m2/repository
variables:
    # Use the cached directory above.
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

deploy:
    before_script:
        # The runners on the forge need a proxy to access the web. mvn
        # ignores the $http_proxy & friends variable => write a
        # configuration file that does this for us.
        - . ci/setup-mvn-proxy.sh
        # Useful only for debugging
         #- cat ~/.m2/settings.xml
        - chmod 400 $CI_SSH_KEY
    script:
        - cd m1if03_tp2 && mvn clean package
        - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY /builds/target/server.war gitlabci@192.168.75.35:/opt/tomcat/webapps/v1.war
        